# Generated by Django 3.0 on 2021-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0002_basemulticontent_textmulti'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedContent',
            fields=[
            ],
            options={
                'ordering': ['-created'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapps.proxybasecontent',),
        ),
    ]
